the branch is meant to say app but i made a typo :(
Model-UN/cimun-web pull request #100
Opened 2023-06-15 04:10 UTC by elysemancilla

Updating the staff app page with staff application and director links

2023-06-16 20:28 UTC, FB-Reda commented on components/articles/staff.app.tsx
> +      <strong>Returning staff:</strong> if you are intereseted in a director position, please fill out the following form:
Can we say "director or other specially-appointed position" now that we're taking applicants for the social media position as part of director apps.

2023-06-16 20:37 UTC, FB-Reda requested changes
Looks real good minus a few code-style level things.  Also please move these files to the app/components folder as I see us moving away from the top-level components folder.

2023-06-16 20:37 UTC, FB-Reda commented on components/articles/staff.app.stories.tsx
This might be a paradigm I'm not familiar with, but can we Pascal Case these files?  So here StaffApp.stories.tsx

2023-06-16 20:37 UTC, FB-Reda commented on components/articles/staff.app.tsx
and here Pascal as StaffApp.tsx

2023-06-18 00:51 UTC, elysemancilla commented on components/articles/staff.app.stories.tsx
all of the others in that folder seem to be this same naming convention, however we can do a cleanup later to fix all of that. id rather maintain consistency at this point and maybe later we can go through and update things

2023-06-20 18:25 UTC, FB-Reda approved these changes

2023-06-20 18:26 UTC, merged