fixes various console errors
Model-UN/cimun-web pull request #113
Opened 2023-07-26 01:36 UTC by jack-carmichael

These are errors shown in the dev environment that should be fixed from this PR.

<img width="866" alt="Screenshot 2023-07-25 at 18 34 49" src="https://github.com/Model-UN/cimun-web/assets/9121099/d1f4daf9-848b-4875-8c96-072d38597ddd">
<img width="866" alt="Screenshot 2023-07-25 at 18 34 36" src="https://github.com/Model-UN/cimun-web/assets/9121099/f03f5f7d-e4a6-4635-a016-1be216b91144">
<img width="888" alt="Screenshot 2023-07-25 at 18 34 31" src="https://github.com/Model-UN/cimun-web/assets/9121099/5a07d282-61f8-43fb-8910-b36a81f4d8e6">
<img width="804" alt="Screenshot 2023-07-25 at 18 34 17" src="https://github.com/Model-UN/cimun-web/assets/9121099/f34267f2-e3eb-41c8-87ae-957c13b9a3de">

The invalid nesting throws an error on prod.

<img width="1711" alt="Screenshot 2023-07-25 at 18 32 13" src="https://github.com/Model-UN/cimun-web/assets/9121099/31db02a2-43f4-4091-9e94-dbf4032a7a37">

2023-07-26 01:37 UTC, FB-Reda commented
king

2023-07-26 01:47 UTC, FB-Reda requested changes

2023-07-26 01:47 UTC, FB-Reda commented on components/headerNav/index.tsx
This change gets rid of pointer behavior, would it make sense to keep the Logo styled-component and instead have that wrap the Next/Image Component?

2023-07-26 01:47 UTC, FB-Reda commented on components/footer/index.tsx
Powered by vercel lost its centering

2023-07-26 01:47 UTC, FB-Reda commented on app/components/staff.app.tsx
altered "letter component" spacing looks suboptimal on mobile widths

2023-07-29 04:09 UTC, jack-carmichael commented on components/headerNav/index.tsx
removed legacyBehavior which fixed the pointer behavior

2023-07-29 04:09 UTC, jack-carmichael commented on components/footer/index.tsx
thought I was removing rogue divs, turns out they were needed ¯\_(ツ)_/¯

2023-07-29 04:09 UTC, jack-carmichael commented on app/components/staff.app.tsx
I think I fixed this? it looks closer now to the live site

2023-07-30 05:03 UTC, FB-Reda requested changes
Still looking for tweaks on the letter component

- Would prefer the margins match the other pages.  I think this is because we're removing the wrapping div so there's 16px on each side unaccounted for.  Maybe this should be simplified as larger padding on the Card idk
- The paragraph text was previously center justified whereas now it's left aligned.

2023-08-03 19:27 UTC, FB-Reda approved these changes
Good work, thanks!

2023-08-03 19:28 UTC, merged